"""add cv parser fields

Revision ID: e0c6344dca9b
Revises: 
Create Date: 2026-08-10 21:24:20.949639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0c6344dca9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('ats_results')
    op.drop_table('job_descriptions')
    op.add_column('cvs', sa.Column('raw_text', sa.Text(), nullable=True))
    op.add_column('cvs', sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cvs', sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('cvs', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cvs', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cvs', 'parsed_at')
    op.drop_column('cvs', 'parsed_data')
    op.drop_column('cvs', 'raw_text')
    op.create_table('job_descriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('job_descriptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_descriptions_pkey'))
    )
    op.create_table('ats_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cv_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], name=op.f('ats_results_cv_id_fkey')),
    sa.ForeignKeyConstraint(['job_id'], ['job_descriptions.id'], name=op.f('ats_results_job_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ats_results_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ats_results_pkey'))
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('applied_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('applications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('applications_pkey'))
    )
    # ### end Alembic commands ###
